#!/bin/sh
cd /var/backups/postgres
echo "SELECT datname FROM pg_database WHERE datistemplate = false;" | psql -t | head -n-1 | sed -e 's/^ \+//' >dbs
cat dbs | while read db; do
	pg_dump -c ${db} >${db}.db
done
pg_dumpall >all.db
