#!/bin/bash
all_folders() {
	find /var/mail/vmail -type d -regextype posix-extended -regex '.*/cur|new$'
}

all_folders | grep "Spam" | sa-learn --spam -f - >/dev/null 2>/dev/null
all_folders | grep -v "Spam" | sa-learn --ham -f - >/dev/null 2>/dev/null
